import os
import re
import shutil
import time
from fastapi import FastAPI, Request
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse, FileResponse
from pydantic import BaseModel
# Correct import for List and Dict
from typing import List, Dict, Any, Optional
import uuid # For generating unique IDs for ChromaDB

from flipkart import get_flipkart_data
from myntra import get_myntra_data
from snapdeal import get_snapdeal_data
# Import the updated utility functions
from utils_1 import (
    parse_query_to_keywords, 
    classify_intent, 
    get_llm, 
    add_message_to_history, 
    get_recent_chat_history,
    add_products_to_chroma,
    get_products_from_chroma,
    generate_bot_response
)

app = FastAPI(title="ShopSmart AI Backend")

# --- Data Models ---
class ChatState(BaseModel):
    session_products: List[Dict[str, Any]] = [] # Still useful for in-session filtering/sorting
    current_view: List[Dict[str, Any]] = []
    display_offset: int = 0
    last_search_keywords: Optional[str] = None
    current_view_summary: Optional[str] = None # Will be generated by LLM

# The ChatResponse structure remains similar, but the content generation is different
class ChatRequest(BaseModel):
    message: str
    state: ChatState

class ChatResponse(BaseModel):
    bot_message: str
    products_to_display: List[Dict[str, Any]]
    new_state: ChatState

# --- Business Logic ---
def parse_price(price_str: Optional[str]) -> int:
    if not isinstance(price_str, str): return float('inf')
    cleaned_price = re.sub(r'[^\d.]', '', price_str)
    try: return int(float(cleaned_price))
    except (ValueError, TypeError): return float('inf')

# --- Main API Endpoint ---
@app.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    user_message = request.message
    state = request.state
    
    print(f"\nReceived message: '{user_message}'")

    # Add user message to ChromaDB history
    user_message_id = str(uuid.uuid4())
    add_message_to_history("Human", user_message, user_message_id)

    bot_message = ""
    products_to_display = []
    PAGE_SIZE = 15
    MIN_CHROMA_RESULTS = PAGE_SIZE # Minimum products to retrieve from Chroma before scraping

    # Get recent chat history for LLM context
    chroma_chat_history = get_recent_chat_history(num_messages=10)

    # Classify intent using LLM and ChromaDB history
    intent = classify_intent(user_message)

    if intent == "greeting":
        bot_message = generate_bot_response(user_message, [], chroma_chat_history, intent)
    
    elif intent == "farewell":
        bot_message = generate_bot_response(user_message, [], chroma_chat_history, intent)
    
    elif intent == 'generic_query':
        keywords = "trending products"
        state.last_search_keywords = keywords
        
        print(f"Handling generic query. Searching for default keywords: '{keywords}'...")
        
        chroma_products = get_products_from_chroma(keywords, n_results=MIN_CHROMA_RESULTS * 2) 
        
        if len(chroma_products) < MIN_CHROMA_RESULTS:
            print(f"Only {len(chroma_products)} trending products in ChromaDB. Scraping more...")
            flipkart_products = get_flipkart_data(keywords)
            myntra_products = get_myntra_data(keywords)
            snapdeal_products = get_snapdeal_data(keywords)
            
            newly_scraped_products = flipkart_products + myntra_products + snapdeal_products
            add_products_to_chroma(newly_scraped_products)
            
            # Re-query Chroma to get a comprehensive set including newly added
            state.session_products = get_products_from_chroma(keywords, n_results=MIN_CHROMA_RESULTS * 2)
        else:
            state.session_products = chroma_products
        
        state.session_products.sort(key=lambda p: parse_price(p.get('price')))
        state.current_view = state.session_products
        state.display_offset = 0

        if not state.session_products:
            bot_message = generate_bot_response(user_message, [], chroma_chat_history, intent, last_search_keywords=keywords)
        else:
            products_to_display = state.session_products[:PAGE_SIZE]
            state.display_offset = len(products_to_display)
            bot_message = generate_bot_response(user_message, products_to_display, chroma_chat_history, intent, last_search_keywords=keywords)
            
    # Handle product search and "show more"
    elif intent == 'product_search':
        keywords = parse_query_to_keywords(user_message)
        state.last_search_keywords = keywords
        print(f"Starting new search for: '{keywords}'...")
        
        chroma_products = get_products_from_chroma(keywords, n_results=MIN_CHROMA_RESULTS * 2)
        
        if len(chroma_products) < MIN_CHROMA_RESULTS:
            print(f"Only {len(chroma_products)} products in ChromaDB for '{keywords}'. Scraping more...")
            flipkart_products = get_flipkart_data(keywords)
            myntra_products = get_myntra_data(keywords)
            snapdeal_products = get_snapdeal_data(keywords)
            
            newly_scraped_products = flipkart_products + myntra_products + snapdeal_products
            add_products_to_chroma(newly_scraped_products)
            
            # Re-query Chroma to get a comprehensive set including newly added
            state.session_products = get_products_from_chroma(keywords, n_results=MIN_CHROMA_RESULTS * 2)
        else:
            state.session_products = chroma_products

        state.session_products.sort(key=lambda p: parse_price(p.get('price')))
        state.current_view = state.session_products
        state.display_offset = 0

        if not state.session_products:
            bot_message = generate_bot_response(user_message, [], chroma_chat_history, intent, last_search_keywords=keywords)
        else:
            products_to_display = state.session_products[:PAGE_SIZE]
            state.display_offset = len(products_to_display)
            bot_message = generate_bot_response(user_message, products_to_display, chroma_chat_history, intent, last_search_keywords=keywords)
            
    elif intent == 'show_more':
        print(f"Showing more results from the current view of {len(state.current_view)} products...")
        if state.display_offset >= len(state.current_view):
            bot_message = generate_bot_response(user_message, state.current_view[max(0, state.display_offset - PAGE_SIZE):state.display_offset], chroma_chat_history, intent, last_search_keywords=state.last_search_keywords)
            products_to_display = [] # No new products to show
        else:
            end_offset = state.display_offset + PAGE_SIZE
            products_to_display = state.current_view[state.display_offset:end_offset]
            state.display_offset = end_offset
            bot_message = generate_bot_response(user_message, products_to_display, chroma_chat_history, intent, last_search_keywords=state.last_search_keywords)
    else: 
        # Fallback for unclear intent or other unhandled cases
        bot_message = generate_bot_response(user_message, [], chroma_chat_history, intent)
        products_to_display = []


    if not products_to_display and not bot_message:
        # If after all logic, still no products and no bot message, provide a default
        bot_message = generate_bot_response(user_message, [], chroma_chat_history, "default", last_search_keywords=state.last_search_keywords)
    
    bot_message_id = str(uuid.uuid4())
    add_message_to_history("AI", bot_message, bot_message_id)

    return ChatResponse(
        bot_message=bot_message,
        products_to_display=products_to_display,
        new_state=state
    )

# --- Serve Static Files ---
app.mount("/static", StaticFiles(directory="static"), name="static")

@app.get("/", response_class=HTMLResponse)
async def read_index():
    return FileResponse('templates/index.html')

if __name__ == '__main__':
    import uvicorn
    print("--- Starting ShopSmart AI Assistant ---")
    print("Your chatbot will be available at: http://127.0.0.1:8000")
    if not os.path.exists(".env.sh"):
        print("\nFATAL ERROR: '.env.sh' not found. Please create one with your API keys.")
    else:
        # Ensure a directory for persistent ChromaDB exists
        os.makedirs("./chroma_db", exist_ok=True) 
        uvicorn.run("backend:app", host="0.0.0.0", port=8000, reload=True)